# Generated by Django 4.2.11 on 2024-05-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0010_employee_child1_employee_child10_employee_child11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='elementary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduate_studies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='vocational_tradecourse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
