# Generated by Django 4.2.11 on 2024-05-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0014_employee_career_service1_employee_career_service2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
