# Generated by Django 4.2.11 on 2024-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0015_alter_employee_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='signature',
            new_name='signature_1',
        ),
        migrations.AddField(
            model_name='employee',
            name='signature_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
