# Generated by Django 4.2.11 on 2024-05-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0016_rename_signature_employee_signature_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='signature_1',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='signature_2',
        ),
    ]
