from django.db import models
from django.contrib.auth.models import User
from datetime import time
# Create your models here.



class Employee(models.Model):
    user = models.OneToOneField(User, null=True, blank=True,unique=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="Default_pfp.jpg", null=True, blank=True)
    employee_id = models.CharField(max_length=20,unique=True)
    surname = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    employment_status = models.CharField(max_length=100, null=True, blank=True)
    name_ext = models.CharField(max_length=10, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    place_of_birth = models.CharField(max_length=100, blank=True, null=True)
    sex = models.CharField(max_length=10, blank=True, null=True)
    civil_status = models.CharField(max_length=20, blank=True, null=True)
    height_m = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    weight_kg = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    blood_type = models.CharField(max_length=10, blank=True, null=True)
    gsis_no = models.CharField(max_length=20, blank=True, null=True)
    pagibig_no = models.CharField(max_length=20, blank=True, null=True)
    philhealth_no = models.CharField(max_length=20, blank=True, null=True)
    sss_no = models.CharField(max_length=20, blank=True, null=True)
    tin_no = models.CharField(max_length=20, blank=True, null=True)
    agency_em = models.CharField(max_length=100, blank=True, null=True)
    citizenship = models.CharField(max_length=50, blank=True, null=True)
    residential_house_no = models.CharField(max_length=10, blank=True, null=True)
    residential_street = models.CharField(max_length=100, blank=True, null=True)
    residential_subd = models.CharField(max_length=100, blank=True, null=True)
    residential_brgy = models.CharField(max_length=100, blank=True, null=True)
    residential_city = models.CharField(max_length=100, blank=True, null=True)
    residential_province = models.CharField(max_length=100, blank=True, null=True)
    residential_zipcode = models.CharField(max_length=10, blank=True, null=True)
    permanent_house_no = models.CharField(max_length=10, blank=True, null=True)
    permanent_street = models.CharField(max_length=100, blank=True, null=True)
    permanent_subd = models.CharField(max_length=100, blank=True, null=True)
    permanent_brgy = models.CharField(max_length=100, blank=True, null=True)
    permanent_city = models.CharField(max_length=100, blank=True, null=True)
    permanent_province = models.CharField(max_length=100, blank=True, null=True)
    permanent_zipcode = models.CharField(max_length=10, blank=True, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)
    mobile_number = models.CharField(max_length=20, blank=True, null=True)
    spouse_surname = models.CharField(max_length=100, blank=True, null=True)
    spouse_first_name = models.CharField(max_length=100, blank=True, null=True)
    spouse_middle_name = models.CharField(max_length=100, blank=True, null=True)
    spouse_name_ext = models.CharField(max_length=10, blank=True, null=True)
    spouse_occupation = models.CharField(max_length=100, blank=True, null=True)
    spouse_employer = models.CharField(max_length=100, blank=True, null=True)
    spouse_business_address = models.CharField(max_length=200, blank=True, null=True)
    spouse_telephone = models.CharField(max_length=20, blank=True, null=True)
    elementary_education = models.CharField(max_length=200, blank=True, null=True)
    secondary_education = models.CharField(max_length=200, blank=True, null=True)
    father_surname = models.CharField(max_length=100, blank=True, null=True)
    father_first_name = models.CharField(max_length=100, blank=True, null=True)
    father_middle_name = models.CharField(max_length=100, blank=True, null=True)
    father_name_ext = models.CharField(max_length=10, blank=True, null=True)
    mother_surname = models.CharField(max_length=100, blank=True, null=True)
    mother_first_name = models.CharField(max_length=100, blank=True, null=True)
    mother_middle_name = models.CharField(max_length=100, blank=True, null=True)
    employment_status = models.CharField(max_length=100, blank=True, null=True)
    child1 = models.CharField(max_length=100, null=True, blank=True)
    child2 = models.CharField(max_length=100, null=True, blank=True)
    child3 = models.CharField(max_length=100, null=True, blank=True)
    child4 = models.CharField(max_length=100, null=True, blank=True)
    child5 = models.CharField(max_length=100, null=True, blank=True)
    child6 = models.CharField(max_length=100, null=True, blank=True)
    child7 = models.CharField(max_length=100, null=True, blank=True)
    child8 = models.CharField(max_length=100, null=True, blank=True)
    child9 = models.CharField(max_length=100, null=True, blank=True)
    child10 = models.CharField(max_length=100, null=True, blank=True)
    child11 = models.CharField(max_length=100, null=True, blank=True)
    child12 = models.CharField(max_length=100, null=True, blank=True)
    child_bday1 = models.DateField(blank=True, null=True)
    child_bday2 = models.DateField(blank=True, null=True)
    child_bday3 = models.DateField(blank=True, null=True)
    child_bday4 = models.DateField(blank=True, null=True)
    child_bday5 = models.DateField(blank=True, null=True)
    child_bday6 = models.DateField(blank=True, null=True)
    child_bday7 = models.DateField(blank=True, null=True)
    child_bday8 = models.DateField(blank=True, null=True)
    child_bday9 = models.DateField(blank=True, null=True)
    child_bday10 = models.DateField(blank=True, null=True)
    child_bday11 = models.DateField(blank=True, null=True)
    child_bday12 = models.DateField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null= True)
    elementary = models.CharField(max_length=100, blank=True, null=True)
    secondary = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse = models.CharField(max_length=100, blank=True, null=True)
    college = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies = models.CharField(max_length=100, blank=True, null=True)
    elementary = models.CharField(max_length=100, blank=True, null=True)
    degree = models.CharField(max_length=100, blank=True, null=True)
    From = models.CharField(max_length=100, blank=True, null=True)
    to = models.CharField(max_length=100, blank=True, null=True)
    units_earned = models.CharField(max_length=100, blank=True, null=True)
    year_graduated = models.CharField(max_length=100, blank=True, null=True)
    scholarship_academic_honor = models.CharField(max_length=100, blank=True, null=True)
    secondary = models.CharField(max_length=100, blank=True, null=True)
    secondary_degree = models.CharField(max_length=100, blank=True, null=True)
    secondary_From = models.CharField(max_length=100, blank=True, null=True)
    secondary_to = models.CharField(max_length=100, blank=True, null=True)
    secondary_units_earned = models.CharField(max_length=100, blank=True, null=True)
    secondary_year_graduated = models.CharField(max_length=100, blank=True, null=True)
    secondary_scholarship_academic_honor = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse_degree = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse_From = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse_to = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse_units_earned = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse_year_graduated = models.CharField(max_length=100, blank=True, null=True)
    vocational_tradecourse_scholarship_academic_honor = models.CharField(max_length=100, blank=True, null=True)
    college = models.CharField(max_length=100, blank=True, null=True)
    college_degree = models.CharField(max_length=100, blank=True, null=True)
    college_From = models.CharField(max_length=100, blank=True, null=True)
    college_to = models.CharField(max_length=100, blank=True, null=True)
    college_units_earned = models.CharField(max_length=100, blank=True, null=True)
    college_year_graduated = models.CharField(max_length=100, blank=True, null=True)
    college_scholarship_academic_honor = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies_degree = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies_From = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies_to = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies_units_earned = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies_year_graduated = models.CharField(max_length=100, blank=True, null=True)
    graduate_studies_scholarship_academic_honor = models.CharField(max_length=100, blank=True, null=True)
    signature = models.ImageField(upload_to='', blank=True, null=True)
    date = models.DateField(blank=True, null=True)

    #pds2
    career_service1 = models.CharField(max_length=100, blank=True, null=True)
    career_service2 = models.CharField(max_length=100, blank=True, null=True)
    career_service3 = models.CharField(max_length=100, blank=True, null=True)
    career_service4 = models.CharField(max_length=100, blank=True, null=True)
    career_service5 = models.CharField(max_length=100, blank=True, null=True)
    career_service6 = models.CharField(max_length=100, blank=True, null=True)
    career_service7 = models.CharField(max_length=100, blank=True, null=True)

    rating_cs1 = models.CharField(max_length=10, blank=True, null=True)
    rating_cs2 = models.CharField(max_length=10, blank=True, null=True)
    rating_cs3 = models.CharField(max_length=10, blank=True, null=True)
    rating_cs4 = models.CharField(max_length=10, blank=True, null=True)
    rating_cs5 = models.CharField(max_length=10, blank=True, null=True)
    rating_cs6 = models.CharField(max_length=10, blank=True, null=True)
    rating_cs7 = models.CharField(max_length=10, blank=True, null=True)

    date_of_exam1 = models.DateField(blank=True, null=True)
    date_of_exam2 = models.DateField(blank=True, null=True)
    date_of_exam3 = models.DateField(blank=True, null=True)
    date_of_exam4 = models.DateField(blank=True, null=True)
    date_of_exam5 = models.DateField(blank=True, null=True)
    date_of_exam6 = models.DateField(blank=True, null=True)
    date_of_exam7 = models.DateField(blank=True, null=True)

    place_of_exam1 = models.CharField(max_length=100, blank=True, null=True)
    place_of_exam2 = models.CharField(max_length=100, blank=True, null=True)
    place_of_exam3 = models.CharField(max_length=100, blank=True, null=True)
    place_of_exam4 = models.CharField(max_length=100, blank=True, null=True)
    place_of_exam5 = models.CharField(max_length=100, blank=True, null=True)
    place_of_exam6 = models.CharField(max_length=100, blank=True, null=True)
    place_of_exam7 = models.CharField(max_length=100, blank=True, null=True)

    license_number1 = models.CharField(max_length=100, blank=True, null=True)
    license_number2 = models.CharField(max_length=100, blank=True, null=True)
    license_number3 = models.CharField(max_length=100, blank=True, null=True)
    license_number4 = models.CharField(max_length=100, blank=True, null=True)
    license_number5 = models.CharField(max_length=100, blank=True, null=True)
    license_number6 = models.CharField(max_length=100, blank=True, null=True)
    license_number7 = models.CharField(max_length=100, blank=True, null=True)

    date_of_validity1 = models.DateField(blank=True, null=True)
    date_of_validity2 = models.DateField(blank=True, null=True)
    date_of_validity3 = models.DateField(blank=True, null=True)
    date_of_validity4 = models.DateField(blank=True, null=True)
    date_of_validity5 = models.DateField(blank=True, null=True)
    date_of_validity6 = models.DateField(blank=True, null=True)
    date_of_validity7 = models.DateField(blank=True, null=True)

    inclusive_dates_from1 = models.DateField(blank=True, null=True)
    inclusive_dates_from2 = models.DateField(blank=True, null=True)
    inclusive_dates_from3 = models.DateField(blank=True, null=True)
    inclusive_dates_from4 = models.DateField(blank=True, null=True)
    inclusive_dates_from5 = models.DateField(blank=True, null=True)
    inclusive_dates_from6 = models.DateField(blank=True, null=True)
    inclusive_dates_from7 = models.DateField(blank=True, null=True)
    inclusive_dates_from8 = models.DateField(blank=True, null=True)
    inclusive_dates_from9 = models.DateField(blank=True, null=True)
    inclusive_dates_from10 = models.DateField(blank=True, null=True)
    inclusive_dates_from11 = models.DateField(blank=True, null=True)
    inclusive_dates_from12 = models.DateField(blank=True, null=True)
    inclusive_dates_from13 = models.DateField(blank=True, null=True)
    inclusive_dates_from14 = models.DateField(blank=True, null=True)
    inclusive_dates_from15 = models.DateField(blank=True, null=True)
    inclusive_dates_from16 = models.DateField(blank=True, null=True)
    inclusive_dates_from17 = models.DateField(blank=True, null=True)
    inclusive_dates_from18 = models.DateField(blank=True, null=True)
    inclusive_dates_from19 = models.DateField(blank=True, null=True)
    inclusive_dates_from20 = models.DateField(blank=True, null=True)
    inclusive_dates_from21 = models.DateField(blank=True, null=True)
    inclusive_dates_from22 = models.DateField(blank=True, null=True)
    inclusive_dates_from23 = models.DateField(blank=True, null=True)
    inclusive_dates_from24 = models.DateField(blank=True, null=True)
    inclusive_dates_from25 = models.DateField(blank=True, null=True)
    inclusive_dates_from26 = models.DateField(blank=True, null=True)
    inclusive_dates_from27 = models.DateField(blank=True, null=True)
    inclusive_dates_from28 = models.DateField(blank=True, null=True)

    inclusive_dates_to1 = models.DateField(blank=True, null=True)
    inclusive_dates_to2 = models.DateField(blank=True, null=True)
    inclusive_dates_to3 = models.DateField(blank=True, null=True)
    inclusive_dates_to4 = models.DateField(blank=True, null=True)
    inclusive_dates_to5 = models.DateField(blank=True, null=True)
    inclusive_dates_to6 = models.DateField(blank=True, null=True)
    inclusive_dates_to7 = models.DateField(blank=True, null=True)
    inclusive_dates_to8 = models.DateField(blank=True, null=True)
    inclusive_dates_to9 = models.DateField(blank=True, null=True)
    inclusive_dates_to10 = models.DateField(blank=True, null=True)
    inclusive_dates_to11 = models.DateField(blank=True, null=True)
    inclusive_dates_to12 = models.DateField(blank=True, null=True)
    inclusive_dates_to13 = models.DateField(blank=True, null=True)
    inclusive_dates_to14 = models.DateField(blank=True, null=True)
    inclusive_dates_to15 = models.DateField(blank=True, null=True)
    inclusive_dates_to16 = models.DateField(blank=True, null=True)
    inclusive_dates_to17 = models.DateField(blank=True, null=True)
    inclusive_dates_to18 = models.DateField(blank=True, null=True)
    inclusive_dates_to19 = models.DateField(blank=True, null=True)
    inclusive_dates_to20 = models.DateField(blank=True, null=True)
    inclusive_dates_to21 = models.DateField(blank=True, null=True)
    inclusive_dates_to22 = models.DateField(blank=True, null=True)
    inclusive_dates_to23 = models.DateField(blank=True, null=True)
    inclusive_dates_to24 = models.DateField(blank=True, null=True)
    inclusive_dates_to25 = models.DateField(blank=True, null=True)
    inclusive_dates_to26 = models.DateField(blank=True, null=True)
    inclusive_dates_to27 = models.DateField(blank=True, null=True)
    inclusive_dates_to28 = models.DateField(blank=True, null=True)

    position_title1 = models.CharField(max_length=50, blank=True, null=True)
    position_title2 = models.CharField(max_length=50, blank=True, null=True)
    position_title3 = models.CharField(max_length=50, blank=True, null=True)
    position_title4 = models.CharField(max_length=50, blank=True, null=True)
    position_title5 = models.CharField(max_length=50, blank=True, null=True)
    position_title6 = models.CharField(max_length=50, blank=True, null=True)
    position_title7 = models.CharField(max_length=50, blank=True, null=True)
    position_title8 = models.CharField(max_length=50, blank=True, null=True)
    position_title9 = models.CharField(max_length=50, blank=True, null=True)
    position_title10 = models.CharField(max_length=50, blank=True, null=True)
    position_title11 = models.CharField(max_length=50, blank=True, null=True)
    position_title12 = models.CharField(max_length=50, blank=True, null=True)
    position_title13 = models.CharField(max_length=50, blank=True, null=True)
    position_title14 = models.CharField(max_length=50, blank=True, null=True)
    position_title15 = models.CharField(max_length=50, blank=True, null=True)
    position_title16 = models.CharField(max_length=50, blank=True, null=True)
    position_title17 = models.CharField(max_length=50, blank=True, null=True)
    position_title18 = models.CharField(max_length=50, blank=True, null=True)
    position_title19 = models.CharField(max_length=50, blank=True, null=True)
    position_title20 = models.CharField(max_length=50, blank=True, null=True)
    position_title21 = models.CharField(max_length=50, blank=True, null=True)
    position_title22 = models.CharField(max_length=50, blank=True, null=True)
    position_title23 = models.CharField(max_length=50, blank=True, null=True)
    position_title24 = models.CharField(max_length=50, blank=True, null=True)
    position_title25 = models.CharField(max_length=50, blank=True, null=True)
    position_title26 = models.CharField(max_length=50, blank=True, null=True)
    position_title27 = models.CharField(max_length=50, blank=True, null=True)
    position_title28 = models.CharField(max_length=50, blank=True, null=True)

    d_a_o_c1 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c2 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c3 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c4 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c5 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c6 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c7 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c8 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c9 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c10 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c11 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c12 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c13 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c14 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c15 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c16 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c17 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c18 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c19 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c20 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c21 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c22 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c23 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c24 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c25 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c26 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c27 = models.CharField(max_length=100, blank=True, null=True)
    d_a_o_c28 = models.CharField(max_length=100, blank=True, null=True)

    monthly_salary1 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary2 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary3 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary4 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary5 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary6 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary7 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary8 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary9 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary10 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary11 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary12 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary13 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary14 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary15 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary16 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary17 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary18 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary19 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary20 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary21 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary22 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary23 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary24 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary25 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary26 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary27 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary28 = models.CharField(max_length=100, blank=True, null=True)

    salary_paygrade1 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade2 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade3 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade4 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade5 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade6 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade7 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade8 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade9 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade10 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade11 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade12 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade13 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade14 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade15 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade16 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade17 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade18 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade19 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade20 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade21 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade22 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade23 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade24 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade25 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade26 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade27 = models.CharField(max_length=50, blank=True, null=True)
    salary_paygrade28 = models.CharField(max_length=50, blank=True, null=True)

    step1 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step2 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step3 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step4 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step5 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step6 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step7 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step8 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step9 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step10 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step11 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step12 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step13 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step14 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step15 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step16 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step17 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step18 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step19 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step20 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step21 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step22 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step23 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step24 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step25 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step26 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step27 = models.CharField(max_length=10, default='00-0', blank=True, null=True)
    step28 = models.CharField(max_length=10, default='00-0', blank=True, null=True)

    status_of_appointment1 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment2 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment3 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment4 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment5 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment6 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment7 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment8 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment9 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment10 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment11 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment12 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment13 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment14 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment15 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment16 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment17 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment18 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment19 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment20 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment21 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment22 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment23 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment24 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment25 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment26 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment27 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment28 = models.CharField(max_length=100, blank=True, null=True)

    gov_service1 = models.CharField(max_length=5, blank=True, null=True)
    gov_service2 = models.CharField(max_length=5, blank=True, null=True)
    gov_service3 = models.CharField(max_length=5, blank=True, null=True)
    gov_service4 = models.CharField(max_length=5, blank=True, null=True)
    gov_service5 = models.CharField(max_length=5, blank=True, null=True)
    gov_service6 = models.CharField(max_length=5, blank=True, null=True)
    gov_service7 = models.CharField(max_length=5, blank=True, null=True)
    gov_service8 = models.CharField(max_length=5, blank=True, null=True)
    gov_service9 = models.CharField(max_length=5, blank=True, null=True)
    gov_service10 = models.CharField(max_length=5, blank=True, null=True)
    gov_service11 = models.CharField(max_length=5, blank=True, null=True)
    gov_service12 = models.CharField(max_length=5, blank=True, null=True)
    gov_service13 = models.CharField(max_length=5, blank=True, null=True)
    gov_service14 = models.CharField(max_length=5, blank=True, null=True)
    gov_service15 = models.CharField(max_length=5, blank=True, null=True)
    gov_service16 = models.CharField(max_length=5, blank=True, null=True)
    gov_service17 = models.CharField(max_length=5, blank=True, null=True)
    gov_service18 = models.CharField(max_length=5, blank=True, null=True)
    gov_service19 = models.CharField(max_length=5, blank=True, null=True)
    gov_service20 = models.CharField(max_length=5, blank=True, null=True)
    gov_service21 = models.CharField(max_length=5, blank=True, null=True)
    gov_service22 = models.CharField(max_length=5, blank=True, null=True)
    gov_service23 = models.CharField(max_length=5, blank=True, null=True)
    gov_service24 = models.CharField(max_length=5, blank=True, null=True)
    gov_service25 = models.CharField(max_length=5, blank=True, null=True)
    gov_service26 = models.CharField(max_length=5, blank=True, null=True)
    gov_service27 = models.CharField(max_length=5, blank=True, null=True)
    gov_service28 = models.CharField(max_length=5, blank=True, null=True)

    signature = models.ImageField(upload_to='', blank=True, null=True)
    e_date = models.DateField(blank=True, null=True)


    organization_name_1 = models.CharField(max_length=150, blank=True, null=True)     #For PDS3 VI row 1
    organization_address_1 = models.CharField(max_length=100, blank=True, null=True)
    from_date_1 = models.DateField(blank=True, null=True)
    to_date_1 = models.DateField(blank=True, null=True)
    number_of_hours_1 = models.PositiveIntegerField(default=0)
    position_nature_of_work_1 = models.CharField(max_length=150, blank=True, null=True)
    organization_name_2 = models.CharField(max_length=150, blank=True, null=True )    #For PDS3 VI row 2
    organization_address_2 = models.CharField(max_length=100, blank=True, null=True)
    from_date_2 = models.DateField(blank=True, null=True)
    to_date_2 = models.DateField(blank=True, null=True)
    number_of_hours_2 = models.PositiveIntegerField(default=0)
    position_nature_of_work_2 = models.CharField(max_length=150, blank=True, null=True)
    organization_name_3 = models.CharField(max_length=150, blank=True, null=True )    #For PDS3 VI row 3
    organization_address_3 = models.CharField(max_length=100, blank=True, null=True)
    from_date_3 = models.DateField(blank=True, null=True)
    to_date_3 = models.DateField(blank=True, null=True)
    number_of_hours_3 = models.PositiveIntegerField(default=0)
    position_nature_of_work_3 = models.CharField(max_length=150, blank=True, null=True)
    organization_name_4 = models.CharField(max_length=150, blank=True, null=True )    #For PDS3 VI row 4
    organization_address_4 = models.CharField(max_length=100, blank=True, null=True)
    from_date_4 = models.DateField(blank=True, null=True)
    to_date_4 = models.DateField(blank=True, null=True)
    number_of_hours_4 = models.PositiveIntegerField(default=0)
    position_nature_of_work_4 = models.CharField(max_length=150, blank=True, null=True)
    organization_name_5 = models.CharField(max_length=150, blank=True, null=True )    #For PDS3 VI row 5
    organization_address_5 = models.CharField(max_length=100, blank=True, null=True)
    from_date_5 = models.DateField(blank=True, null=True)
    to_date_5 = models.DateField(blank=True, null=True)
    number_of_hours_5 = models.PositiveIntegerField(default=0)
    position_nature_of_work_5 = models.CharField(max_length=150, blank=True, null=True)
    organization_name_6 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VI row 6
    organization_address_6 = models.CharField(max_length=100, blank=True, null=True)
    from_date_6 = models.DateField(blank=True, null=True)
    to_date_6 = models.DateField(blank=True, null=True)
    number_of_hours_6 = models.PositiveIntegerField(default=0)
    position_nature_of_work_6 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VI row 7
    organization_name_7 = models.CharField(max_length=150, blank=True, null=True)
    organization_address_7 = models.CharField(max_length=100, blank=True, null=True)
    from_date_7 = models.DateField(blank=True, null=True)
    to_date_7 = models.DateField(blank=True, null=True)
    number_of_hours_7 = models.PositiveIntegerField(default=0)
    position_nature_of_work_7 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_1 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 1
    from_date_A1 = models.DateField(blank=True, null=True)
    to_date_A1 = models.DateField(blank=True, null=True)
    number_of_hours_A1 = models.PositiveIntegerField(default=0)
    type_of_ld_1 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_1 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_2 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 2
    from_date_A2 = models.DateField(blank=True, null=True)
    to_date_A2 = models.DateField(blank=True, null=True)
    number_of_hours_A2 = models.PositiveIntegerField(default=0)
    type_of_ld_2 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_2 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_3 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 3
    from_date_A3 = models.DateField(blank=True, null=True)
    to_date_A3 = models.DateField(blank=True, null=True)
    number_of_hours_A3 = models.PositiveIntegerField(default=0)
    type_of_ld_3 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_3 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_4 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 4
    from_date_A4 = models.DateField(blank=True, null=True)
    to_date_A4 = models.DateField(blank=True, null=True)
    number_of_hours_A4 = models.PositiveIntegerField(default=0)
    type_of_ld_4 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_4 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_5 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 5
    from_date_A5 = models.DateField(blank=True, null=True)
    to_date_A5 = models.DateField(blank=True, null=True)
    number_of_hours_A5 = models.PositiveIntegerField(default=0)
    type_of_ld_5 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_5 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_6 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 6
    from_date_A6 = models.DateField(blank=True, null=True)
    to_date_A6 = models.DateField(blank=True, null=True)
    number_of_hours_A6 = models.PositiveIntegerField(default=0)
    type_of_ld_6 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_6 = models.CharField(max_length=150, blank=True, null=True)
    title_of_program_7 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VII row 7
    from_date_A7 = models.DateField(blank=True, null=True)
    to_date_A7 = models.DateField(blank=True, null=True)
    number_of_hours_A7 = models.PositiveIntegerField(default=0)
    type_of_ld_7 = models.CharField(max_length=150, blank=True, null=True)
    conducted_by_7 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_1 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VIII row 1
    special_skills_1 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_1 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_2 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VIII row 2
    special_skills_2 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_2 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_3 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VIII row 3
    special_skills_3 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_3 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_4 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VIII row 4
    special_skills_4 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_4 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_5 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VIII row 5
    special_skills_5 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_5 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_6 = models.CharField(max_length=150, blank=True, null=True)    #For PDS3 VIII row 6
    special_skills_6 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_6 = models.CharField(max_length=150, blank=True, null=True)
    non_academic_distinctions_7 = models.CharField(max_length=150, blank=True, null=True)     #For PDS3 VIII row 7
    special_skills_7 = models.CharField(max_length=150, blank=True, null=True)
    membership_association_7 = models.CharField(max_length=150, blank=True, null=True)

    #pds4 gawa ni Yen
    reference_name1 = models.CharField(max_length=150, blank=True, null=True)
    reference_name2 = models.CharField(max_length=150, blank=True, null=True)
    reference_name3 = models.CharField(max_length=150, blank=True, null=True)
    reference_address1 = models.CharField(max_length=250, blank=True, null=True)
    reference_address2 = models.CharField(max_length=250, blank=True, null=True)
    reference_address3 = models.CharField(max_length=250, blank=True, null=True)
    reference_tel_no1 = models.CharField(max_length=250, blank=True, null=True)
    reference_tel_no2 = models.CharField(max_length=250, blank=True, null=True)
    reference_tel_no3 = models.CharField(max_length=250, blank=True, null=True)
    goverment_issued_id = models.CharField(max_length=250, blank=True, null=True)
    ID_License_Passport_no = models.CharField(max_length=250, blank=True, null=True)
    Date_Place_of_insurance = models.CharField(max_length=250, blank=True, null=True)

    signature = models.ImageField(upload_to='', blank=True, null=True)
    date_accomplished = models.DateField(blank=True, null=True)
    right_thumbmark = models.ImageField(upload_to='', blank=True, null=True)

    Person_admin_oath = models.CharField(max_length=250, blank=True, null=True)


    def __str__(self):
        return f"{self.employee_id} - {self.first_name} {self.surname}"


class OfficialTime(models.Model):
    employee_id = models.CharField(max_length=20)
    day = models.CharField(max_length = 10)
    semester_id = models.CharField(max_length = 10, null= True, blank = True)
    official_office_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_office_out = models.TimeField(default='00:00:00', null=True, blank=True)
    official_honorarium_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_honorarium_time_out = models.TimeField(default='00:00:00', null=True, blank=True)
    official_servicecredit_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_servicecredit_time_out = models.TimeField(default='00:00:00', null=True, blank=True)
    official_overtime_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_overtime_time_out = models.TimeField(default='00:00:00', null=True, blank=True)


class AttendanceRecord(models.Model):
    employee_id = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    break_in = models.TimeField(default='00:00:00', null=True, blank=True)
    break_out = models.TimeField(default='00:00:00', null=True, blank=True)
    time_out = models.TimeField(default='00:00:00', null=True, blank=True)
    surplusHour_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    surplusHour_time_out = models.TimeField(default='00:00:00', null=True, blank=True)

    def __str__(self):
        return f"{self.employee_id} - {self.date}" if self.date else self.employee_id


class EditLogs(models.Model):
    attendance_record = models.ForeignKey(AttendanceRecord, on_delete=models.CASCADE)
    edited_by = models.ForeignKey(User, on_delete=models.CASCADE)
    logged_data = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)